Traceback (most recent call last):
  File "C:\Users\Nav\AppData\Local\Programs\Python\Python312\Lib\site-packages\mypy\__main__.py", line 15, in console_entry
    main()
  File "mypy\main.py", line 119, in main
  File "mypy\main.py", line 203, in run_build
  File "mypy\build.py", line 191, in build
  File "mypy\build.py", line 267, in _build
  File "mypy\build.py", line 2884, in dispatch
  File "mypy\build.py", line 3152, in load_graph
  File "mypy\build.py", line 1921, in __init__
  File "mypy\build.py", line 2622, in find_module_and_diagnose
  File "mypy\build.py", line 2728, in find_module_with_reason
  File "mypy\modulefinder.py", line 320, in find_module
  File "mypy\modulefinder.py", line 534, in _find_module
  File "mypy\fscache.py", line 199, in isfile_case
  File "mypy\fscache.py", line 180, in isfile
  File "mypy\fscache.py", line 71, in stat_or_none
KeyboardInterrupt
Interrupted
